import { ACMEvent, GalleryItem, ACMProject, TeamMember } from "@/types";

export const EVENTS_DATA: ACMEvent[] = [
  {
    id: "event-01",
    title: "State of Computation: Neural Architectures & Systems",
    date: "OCTOBER 24, 2026",
    time: "17:00 — 19:30 UTC",
    venue: "Main Engineering Hall · Stream A",
    category: "Colloquium",
    description:
      "A technical examination of transformer efficiency, sparse attention, and low-latency edge inference models for next-generation systems.",
    status: "Open for RSVP",
    rsvpUrl: "#rsvp",
    highlights: ["Kernel Tuning", "Attention Benchmarks", "Open Model Dissections"],
  },
  {
    id: "event-02",
    title: "Algorithmic Rigor: Graph Topologies & Distributed Consensus",
    date: "NOVEMBER 12, 2026",
    time: "14:00 — 18:00 UTC",
    venue: "Computing Systems Lab 04",
    category: "Workshop",
    description:
      "Hands-on workshop breaking down Byzantine fault tolerance, Raft implementations in systems languages, and partition survivability.",
    status: "Open for RSVP",
    rsvpUrl: "#rsvp",
    highlights: ["Raft in Rust", "Network Partition Simulation", "Formal Verification"],
  },
  {
    id: "event-03",
    title: "ACM FACE Winter Hack: Computational Interfaces",
    date: "DECEMBER 05–07, 2026",
    time: "48 Hours Continuous",
    venue: "Design & Innovation Annex",
    category: "Hackathon",
    description:
      "Annual chapter build convening student researchers, systems engineers, and interface designers around human-computational tools.",
    status: "Upcoming",
    rsvpUrl: "#rsvp",
    highlights: ["Zero-Bloat UX", "Hardware Conduits", "Local-First Software"],
  },
  {
    id: "event-04",
    title: "Ethics in Autonomous Agents: Societal Impact Forum",
    date: "JANUARY 18, 2027",
    time: "16:00 — 18:00 UTC",
    venue: "Humanities & Sciences Auditorium",
    category: "Symposium",
    description:
      "Interdisciplinary forum addressing alignment, algorithmic bias in governance, and democratic accountability in agentic software.",
    status: "Upcoming",
    rsvpUrl: "#rsvp",
    highlights: ["Keynote Faculty Panel", "Student Working Papers", "Policy Open Mic"],
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "gal-01",
    title: "Inaugural Chapter Colloquium",
    caption: "Deep dive into distributed systems & student computing charter.",
    date: "FALL 2025",
    category: "Convening",
    dimensions: "16:9",
    accent: "#a3a3a3",
  },
  {
    id: "gal-02",
    title: "Systems Lab Session: Kernel Space",
    caption: "Profiling cache misses and memory hierarchies on bare metal.",
    date: "WINTER 2025",
    category: "Workshop",
    dimensions: "4:3",
    accent: "#737373",
  },
  {
    id: "gal-03",
    title: "Human-Computer Interaction Showcase",
    caption: "Physical computing prototypes exploring non-tactile spatial inputs.",
    date: "SPRING 2026",
    category: "Exhibition",
    dimensions: "1:1",
    accent: "#d4d4d4",
  },
  {
    id: "gal-04",
    title: "Algorithmic Code Sprint",
    caption: "Peer-led competitive programming and graph algorithm dissection.",
    date: "SPRING 2026",
    category: "Hackathon",
    dimensions: "16:9",
    accent: "#a3a3a3",
  },
  {
    id: "gal-05",
    title: "Research Paper Reading Group",
    caption: "Deconstructing classic papers from Turing, Dijkstra, and Shannon.",
    date: "SUMMER 2026",
    category: "Seminar",
    dimensions: "4:3",
    accent: "#737373",
  },
  {
    id: "gal-06",
    title: "Collaborative Terminal Architecture",
    caption: "Open-source development sprint on chapter computational tools.",
    date: "AUTUMN 2026",
    category: "Build",
    dimensions: "16:9",
    accent: "#d4d4d4",
  },
];

export const PROJECTS_DATA: ACMProject[] = [
  {
    id: "prj-01",
    title: "Synapse-CLI",
    code: "SYS-01",
    status: "Public Alpha",
    category: "Developer Tooling",
    description:
      "A keyboard-driven terminal telemetry companion for monitoring distributed cluster workloads with minimal CPU footprint.",
    techStack: ["Rust", "eBPF", "TUI", "WebAssembly"],
    githubUrl: "https://github.com",
    demoUrl: "#demo",
    offset: { x: -280, y: -160, rotate: -3 },
  },
  {
    id: "prj-02",
    title: "Graphite Engine",
    code: "SYS-02",
    status: "Active Research",
    category: "Graph Computation",
    description:
      "An in-memory property graph engine designed to model chapter member interactions and project dependencies with sub-millisecond traversal.",
    techStack: ["TypeScript", "Linear Algebra", "Vector Math"],
    githubUrl: "https://github.com",
    demoUrl: "#demo",
    offset: { x: 280, y: -140, rotate: 2 },
  },
  {
    id: "prj-03",
    title: "Aether OS Interface",
    code: "SYS-03",
    status: "Prototype",
    category: "HCI & Design Systems",
    description:
      "An experimental spatial desktop surface treating documents as interconnected computational nodes rather than hierarchical folders.",
    techStack: ["SVG Canvas", "WebGPU", "Reactive State"],
    githubUrl: "https://github.com",
    demoUrl: "#demo",
    offset: { x: -290, y: 150, rotate: 2 },
  },
  {
    id: "prj-04",
    title: "Krypton Consensus",
    code: "SYS-04",
    status: "Core System",
    category: "Distributed Consensus",
    description:
      "Lightweight pedagogical Raft implementation featuring live network visualizers for teaching distributed algorithms in undergraduate seminars.",
    techStack: ["Go", "gRPC", "WebSocket", "SVG"],
    githubUrl: "https://github.com",
    demoUrl: "#demo",
    offset: { x: 290, y: 160, rotate: -2 },
  },
];

export const TEAM_MEMBERS_DATA: TeamMember[] = [
  // Row 1: Executive Leadership
  {
    id: "tm-01",
    name: "Dr. A. K. Sharma",
    role: "Chapter Faculty Sponsor",
    tier: "Executive",
    discipline: "Distributed Systems & Parallel Architecture",
    bio: "Guiding the ACM Student Chapter charter, curriculum initiatives, and institutional research affiliations.",
    row: 1,
    initials: "AS",
    socials: { email: "faculty@jit.acm.org" },
  },
  {
    id: "tm-02",
    name: "Chairperson (Candidate)",
    role: "Chapter Chair",
    tier: "Executive",
    discipline: "Systems Engineering",
    bio: "Directing strategic roadmap, chapter stewardship, and inter-chapter partnerships across ACM networks.",
    row: 1,
    initials: "CC",
    socials: { github: "https://github.com", linkedin: "https://linkedin.com" },
  },
  {
    id: "tm-03",
    name: "Vice Chair (Candidate)",
    role: "Vice Chairperson",
    tier: "Executive",
    discipline: "Computer Science & Design",
    bio: "Overseeing chapter programming, symposium colloquia, and community onboarding.",
    row: 1,
    initials: "VC",
    socials: { github: "https://github.com", linkedin: "https://linkedin.com" },
  },
  {
    id: "tm-04",
    name: "Treasurer (Candidate)",
    role: "Finance & Logistics Officer",
    tier: "Executive",
    discipline: "Economics & Computing",
    bio: "Stewardship of chapter grants, project funding allocations, and annual symposium operations.",
    row: 1,
    initials: "TR",
    socials: { email: "treasury@jit.acm.org" },
  },

  // Row 2: Technical Leads
  {
    id: "tm-05",
    name: "Technical Director (Candidate)",
    role: "Head of Systems & Infrastructure",
    tier: "Technical",
    discipline: "Kernel & Network Protocols",
    bio: "Architecting chapter internal platforms, server infrastructure, and open-source tooling.",
    row: 2,
    initials: "TD",
    socials: { github: "https://github.com" },
  },
  {
    id: "tm-06",
    name: "AI / ML Research Lead (Candidate)",
    role: "Machine Intelligence Lead",
    tier: "Technical",
    discipline: "Statistical Learning & NLP",
    bio: "Facilitating paper reading groups, model evaluations, and applied generative experiments.",
    row: 2,
    initials: "ML",
    socials: { github: "https://github.com" },
  },
  {
    id: "tm-07",
    name: "Algorithms Lead (Candidate)",
    role: "Competitive Programming Lead",
    tier: "Technical",
    discipline: "Graph Theory & Combinatorics",
    bio: "Mentoring ICPC squads and hosting weekly algorithmic problem breakdowns.",
    row: 2,
    initials: "AL",
    socials: { github: "https://github.com" },
  },
  {
    id: "tm-08",
    name: "Web & Platform Lead (Candidate)",
    role: "Interface Engineering Lead",
    tier: "Technical",
    discipline: "Creative Technology & Web Performance",
    bio: "Maintaining the ACM FACE digital surface and component design systems.",
    row: 2,
    initials: "WP",
    socials: { github: "https://github.com" },
  },

  // Row 3: Design, Operations & Community
  {
    id: "tm-09",
    name: "Design Director (Candidate)",
    role: "Design & Creative Systems Lead",
    tier: "Design & Operations",
    discipline: "Human-Computer Interaction",
    bio: "Defining editorial aesthetics, publication identity, and tactile event collateral.",
    row: 3,
    initials: "DD",
    socials: { linkedin: "https://linkedin.com" },
  },
  {
    id: "tm-10",
    name: "Events Lead (Candidate)",
    role: "Colloquia & Convenings Lead",
    tier: "Design & Operations",
    discipline: "Operations & Communications",
    bio: "Managing hackathon logistics, speaker hospitality, and venue staging.",
    row: 3,
    initials: "EL",
    socials: { email: "events@jit.acm.org" },
  },
  {
    id: "tm-11",
    name: "Community Steward (Candidate)",
    role: "Outreach & Inclusivity Lead",
    tier: "Design & Operations",
    discipline: "Sociotechnical Studies",
    bio: "Fostering cross-departmental membership, mentorship pairings, and student outreach.",
    row: 3,
    initials: "CS",
    socials: { linkedin: "https://linkedin.com" },
  },
  {
    id: "tm-12",
    name: "Documentation Archivist (Candidate)",
    role: "Historian & Archivist",
    tier: "Design & Operations",
    discipline: "Technical Writing & Archival Science",
    bio: "Documenting chapter research artifacts, project records, and retrospective timelines.",
    row: 3,
    initials: "DA",
    socials: { github: "https://github.com" },
  },
];
