import { EventItem } from "@/types";

export const EVENTS_DATA: EventItem[] = [
  {
    slug: "event-1",
    title: "Event title",
    dateISO: null,
    dateLabel: "Date TBA",
    summary: "Event description and technical agenda will be announced soon.",
    mode: "In-Person & Stream",
    location: "Venue TBA",
    status: "open",
    registerUrl: "#rsvp",
    placeholder: true,
  },
  {
    slug: "event-2",
    title: "Event title",
    dateISO: null,
    dateLabel: "Date TBA",
    summary: "Event description and technical agenda will be announced soon.",
    mode: "In-Person",
    location: "Venue TBA",
    status: "open",
    registerUrl: "#rsvp",
    placeholder: true,
  },
  {
    slug: "event-3",
    title: "Event title",
    dateISO: null,
    dateLabel: "Date TBA",
    summary: "Event description and technical agenda will be announced soon.",
    mode: "Convening",
    location: "Venue TBA",
    status: "open",
    registerUrl: "#rsvp",
    placeholder: true,
  },
  {
    slug: "event-4",
    title: "Event title",
    dateISO: null,
    dateLabel: "Date TBA",
    summary: "Event description and technical agenda will be announced soon.",
    mode: "Colloquium",
    location: "Venue TBA",
    status: "closing-soon",
    registerUrl: "#rsvp",
    placeholder: true,
  },
  {
    slug: "event-5",
    title: "Event title",
    dateISO: null,
    dateLabel: "Date TBA",
    summary: "Archived chapter session and convening records.",
    mode: "Archived Colloquium",
    location: "Venue TBA",
    status: "past",
    placeholder: true,
  },
];

export const FALLBACK_PLACEHOLDER_EVENTS: EventItem[] = EVENTS_DATA;
